name: dslnapari
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - scikit-image
  - pandas
  - matplotlib
  - napari
  - pyqt
  - copier 
  - jinja2-time
  - npe2
  - pip
  - pip:
      - napari-skimage