name: dslnapari
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - scikit-image
  - pandas
  - matplotlib
  - napari
  - pyqt
  - aicsimageio
  - ipywidgets
  - pip:
      - napari-crop